name: "Download msvc-wine and cache it"
author: laz
description: "Download msvc-wine and cache it, or restore it from the cache"
runs:
  using: composite
  steps:
    - name: "Install package dependencies"
      run: |
        sudo dpkg --add-architecture i386 && sudo apt-get update
        sudo apt install -y wine64 wine32 python3 msitools ca-certificates cmake ninja-build winbind meson 7zip
        wine64 wineboot
        curl -s -L -O https://github.com/madewokherd/wine-mono/releases/download/wine-mono-5.1.1/wine-mono-5.1.1-x86.msi
        wine64 msiexec /i wine-mono-5.1.1-x86.msi

      shell: bash

    - name: "Restore msvc-wine cache"
      id: dependency-msvc-wine
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/msvc
        key: dependency-msvc-wine

    - name: "Clone msvc-wine"
      if: steps.dependency-msvc-wine.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: 'mstorsjo/msvc-wine'
        path: 'msvc-wine'

    - name: "Run msvc-wine setup"
      if: steps.dependency-msvc-wine.outputs.cache-hit != 'true'
      run: |
        ${{ github.workspace }}/msvc-wine/vsdownload.py --accept-license --dest ${{ github.workspace }}/msvc
        ${{ github.workspace }}/msvc-wine/install.sh ${{ github.workspace }}/msvc
      shell: bash

    - name: "Setup x86 MSVC environment"
      id: 'msvc_setup'
      run: |
        source ${{ github.workspace }}/msvc/bin/x86/msvcenv.sh
        echo "INCLUDE=$INCLUDE" >> $GITHUB_ENV
        echo "MSVC=${{ github.workspace }}/msvc" >> $GITHUB_ENV
        echo "CC=${{ github.workspace }}/msvc/bin/x86/cl" >> $GITHUB_ENV
        echo "CXX=${{ github.workspace }}/msvc/bin/x86/cl" >> $GITHUB_ENV
        echo "RC=${{ github.workspace }}/msvc/bin/x86/rc" >> $GITHUB_ENV
        echo "LD=${{ github.workspace }}/msvc/bin/x86/link" >> $GITHUB_ENV
      shell: bash